version: "3.1"

services:
  db:
    image: mariadb:10.3.16
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oriAdmin2010
    volumes:
      - /Users/origin/Desktop/Archive/db:/var/lib/mysql
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
